import '@/app/globals.scss';
import ToastWrapper from '@/libs/ToastWrapper';
import 'react-toastify/ReactToastify.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/tokyo-night-dark.min.css"
        />
      </head>
      <body>
        {children}
        <ToastWrapper />
      </body>
    </html>
  );
}
