import '@/app/globals.scss';
import AdminTemplate from '@/app/UI/Common/AdminTemplate';
import QueryWrapper from '@/libs/QueryWrapper';
import SessionWrapper from '@/libs/SessionWrapper';
import ToastWrapper from '@/libs/ToastWrapper';
import 'react-toastify/ReactToastify.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/tokyo-night-dark.min.css"
        />
      </head>
      <body>
        <SessionWrapper>
          <QueryWrapper>
            <AdminTemplate>{children}</AdminTemplate>
            <ToastWrapper />
          </QueryWrapper>
        </SessionWrapper>
      </body>
    </html>
  );
}
